#!/bin/bash

# Change home directory (bower puts a lot of cache and tmp directories here)
HOME=$OPENSHIFT_REPO_DIR
cd $OPENSHIFT_REPO_DIR

mkdir -p "$OPENSHIFT_DATA_DIR"node_modules

ln -s "$OPENSHIFT_DATA_DIR"node_modules node_modules

npm install --loglevel error

